### ISSUE TITLE
No reasonable way to use `OTEL_LOG_LEVEL`

### ISSUE THREAD

**Issue by jtmalinowski** [open-telemetry/opentelemetry-js-api#102]
Problem 1: just setting the logger uses a default level instead of the one from env configuration (<https://github.com/open-telemetry/opentelemetry-js-api/blob/main/src/api/diag.ts#L75>). Which means when setting a logger you need to fetch the ENV variable by yourself 

```
diag.setLogger(new DiagConsoleLogger(), getEnv().OTEL_LOG_LEVEL);
```

which sort of defeats the point of the ENV variable?

Problem 2: tangentially, after `setLogLevel` was removed, there's no way to set the level and the logger independently (<https://github.com/open-telemetry/opentelemetry-js-api/pull/9>), which will make integration with Node ENV configuration tricky.

I'd propose:
- reviving `setLogLevel` 
- change `setLogger` so that second argument, unless provided, doesn't change the log level
- allow `setLogLevel` and `setLogger` to be called in any order

Also, I'm happy to hear your thoughts, and send a PR when a resolution is decided.

ping @dyladan

**Comment by longility** [comment]
If the logger is not set, should we be defaulting to a noop logger or `DiagConsoleLogger`?

**Comment by longility** [comment]
Another option could be if env var `OTEL_LOG_LEVEL` is set than we default to `DiagConsoleLogger`. If not set, then default to noop.

**Comment by dyladan** [comment]
> Another option could be if env var `OTEL_LOG_LEVEL` is set than we default to `DiagConsoleLogger`. If not set, then default to noop.

Seems a reasonable compromise

**Comment by longility** [comment]
Acceptance criteria for whoever ends up tackling.

I may have time next week.

- [ ] If `OTEL_LOG_LEVEL` is defined, then default to `DiagConsoleLogger`.
- [ ] Logger defined should overwrite the default logger.
- [ ] If `OTEL_LOG_LEVEL` is not defined, then default to `NoopLogger`.
- [ ] `setLogger` to maintain existing log level and not overwrite with parameter default. (i.e. setLogger without log level provides should not overwrite the defined `OTEL_LOG_LEVEL`)
- [ ] Revive setLogLevel and allow setLogger and setLogLevel to be called and set in any order. Natural set order.

**Comment by longility** [comment]
> If `OTEL_LOG_LEVEL` is defined, then default to `DiagConsoleLogger`.

I'm actually trying to figure out where this should go as `getEnv()` is in `@opentelemetry/core` and there isn't a pattern that I know of that is gets executed "automatically" without end user trigger from configuration. 

Basically, without otel configuration and only env var `OTEL_LOG_LEVEL` where do we call something like `if(getEnv().OTEL_LOG_LEVEL) diag.setLogger(new DiagConsoleLogger(), getEnv().OTEL_LOG_LEVEL);`?

Personally, this is the only acceptance criteria that I desire among the others and it may be the 80% case. I think the other acceptance criterias are 20% case.

**Comment by jonaskello** [comment]
I tried for the longest time to make `OTEL_LOG_LEVEL` and finally found this issue. Added the code below and now it works:

```ts
  api.diag.setLogger(new DiagConsoleLogger(), getEnv().OTEL_LOG_LEVEL);
```
