### ISSUE TITLE
No way to add a `Link` to an already-created `Span`

### ISSUE THREAD

**Issue by Sushisource** [open-telemetry/opentelemetry-js-api#124]
As far as I can tell the only (typescript safe) way to link spans is to pass the link when creating the span as here: https://open-telemetry.github.io/opentelemetry-js-api/interfaces/tracer.html#startspan

However, it's desirable in many situations to be able to associate spans *after* they are created. I couldn't find any way to do this.

I would expect to be able to do something like:
```ts
span.link(otherSpanContext)
```

If there's a way to do this already please let me know. I could contribute this if it makes sense

**Comment by lonewolf3739** [comment]
@Sushisource See this https://github.com/open-telemetry/opentelemetry-specification/issues/454 and this https://github.com/open-telemetry/opentelemetry-specification/issues/826

**Comment by Sushisource** [comment]
@lonewolf3739 Wow, thanks. This seems like such a clear thing to want to do that I just assumed it was part of the spec. What's funny is this actually already works if you bypass TS and just manually insert the links into the span, but I can see how sampling etc complicates things.

Feel free to close this in lieu of the issues on the spec if desired
