### ISSUE TITLE
Support spec v1.4.0 schema url in tracer

### ISSUE THREAD

**Issue by legendecas** [open-telemetry/opentelemetry-js-api#125]
Spec [v1.4.0](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md#v140-2021-06-07) added a new optional parameter to `TracerProvider.getTracer`, ([link](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer)).

However, in a similar situation, implementations like https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-sdk-metrics-base/src/MeterProvider.ts#L48 may already extending the `MeterProvider.getMeter` with positional parameters, so adding new positional parameter `schemaUrl` in `@opentelemetry/api-metrics` would conflict with those implementations. (Related: https://github.com/open-telemetry/opentelemetry-js/pull/2529)

The good news is that `BasicTracerProvider.getTracer` in https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts#L93 didn't extend the method with positional parameters.  So we can still extend the method with optional positional parameters:
```typescript
interface TracerProvider {
  getTracer(name: string, version?: string, schemaUrl?: string): Tracer;
}
```

Still, the approach above leaves us a dilemma when a new optional parameter is added in the future. For better extensibility and to keep compatibility, we can override the function with a variable second parameter type like the following example.

```typescript
interface TracerProvider {
  getTracer(name: string, version?: string): Tracer;
  getTracer(name: string, options?: TracerOptions): Tracer;
}
```

**Comment by Flarna** [comment]
Actually every semver minor change in API is currently breaking for the end user.

Consider API 1.1.0 with above change is released but the corresponding change in SDK is not yet done.
An user installing latest available components of API and SDK will get 1.1.0 of API which fits to older SDK (from NPM point of view) because package.json there has `"@opentelemetry/api": "^1.0.2"` in `peerDependencies`.

So it's don't care if `getTracer('foo', 1, 'fooUrl')` is used or `getTracer('foo', { version: 1, schemaUrl: 'fooUrl'})` because SDK will no honor schemaUrl which is not what users expect as they use API 1.1.0.

I think we should use `~` instead `^` in the version selector of API in core and contrib to avoid this problem.

**Comment by Flarna** [comment]
created https://github.com/open-telemetry/opentelemetry-js/pull/2531 to avoid automatic updates to now minor API versions in SDK.

**Comment by dyladan** [comment]
@Flarna in this case I think actually an additional parameter is ok. A class which implements an interface is not required to have the same number of arguments for all functions.

```typescript
interface NewApi {
    functionWithNewParameter(param1: string, param2: string): void;
}


class OldApi implements NewApi {
    // no compilation error
    functionWithNewParameter(param1: string): void { }
}
```

**Comment by Flarna** [comment]
> So it's don't care if `getTracer('foo', 1, 'fooUrl')` is used or `getTracer('foo', { version: 1, schemaUrl: 'fooUrl'})` because SDK will no honor schemaUrl which is not what users expect as they use API 1.1.0.

This point still holds. There is no build problem but it's still confusing behavior. 

But as we have limited the upper bound of the API used by SDK it should be fine.

**Comment by dyladan** [comment]
API/SDK/Instrumentation version compatibility is a very confusing story at the moment. I really would like a way to make it less confusing.

**Comment by vmarchaud** [comment]
> API/SDK/Instrumentation version compatibility is a very confusing story at the moment.

Did the TC/spec give any guidance on this ? I remember that we talked about it some time ago but only between the sdk/api

**Comment by legendecas** [comment]
@vmarchaud  Do you refer to this discussion? https://github.com/open-telemetry/opentelemetry-specification/issues/2018. However, I didn't find it to be settled with a resolution.

**Comment by vmarchaud** [comment]
> Do you refer to this discussion?

Yes, maybe @dyladan have more information about this from the maintainer SIG ?

**Comment by dyladan** [comment]
> > API/SDK/Instrumentation version compatibility is a very confusing story at the moment.
> 
> Did the TC/spec give any guidance on this ? I remember that we talked about it some time ago but only between the sdk/api

What I meant by this is that the JS versioning is very confusing. It's hard for JS users to know which version of the API is compatible with which version of the SDK and which instrumentations will work. Other languages have solved this in different ways. For example in Go the instrumentations are compiled into the SDK. In Java IIRC they have an autoinstrumentation agent which bundles a bunch of instrumentations with the appropriate SDK version.

> > Do you refer to this discussion?
> 
> Yes, maybe @dyladan have more information about this from the maintainer SIG ?

It was discussed in the maintainer SIG but there really wasn't a consensus. IIRC the takeaway was that it might not be possible to do the exact same thing for every language, but I think that discussion isn't really relevant to this issue. That discussion wasn't really about if we are allowed to add features and increment versions as much as how we version the API and SDK to make sure that users have compatible versions at runtime if the installation is successful. Our approach of incrementing the minor API version when a non-breaking change is made and targeting a maximum API version for each release of the SDK seems to be what other SIGs are doing as well.
