### ISSUE TITLE
Move `Attributes` to common location

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-api#130]
The specification now uses a common definition of `Attributes` for traces and metrics. Our definition of attributes should be moved from the `trace` directory to a `common` directory to reflect this.

**Comment by naseemkullah** [comment]
done? https://github.com/open-telemetry/opentelemetry-js-api/blob/main/src/common/Attributes.ts

**Comment by legendecas** [comment]
Fixed with https://github.com/open-telemetry/opentelemetry-js-api/pull/142.
