### ISSUE TITLE
Error "Attempted duplicate registration of API" in AWS Lambda Layer

### ISSUE THREAD

**Issue by raulrojasadl** [open-telemetry/opentelemetry-js-api#157]
Hi friends,

We are working with aws-otel-nodejs-amd64-ver-1-0-1 and currently it generate this error

`2022-02-25T16:50:46.804Z	undefined	ERROR	Error: @opentelemetry/api: Attempted duplicate registration of API: propagation
    at Object.registerGlobal (/opt/nodejs/node_modules/@opentelemetry/api/build/src/internal/global-utils.js:33:19)
    at PropagationAPI.setGlobalPropagator (/opt/nodejs/node_modules/@opentelemetry/api/build/src/api/propagation.js:51:31)
    at NodeTracerProvider.register (/opt/nodejs/node_modules/@opentelemetry/sdk-trace-base/build/src/BasicTracerProvider.js:99:31)
    at NodeTracerProvider.register (/opt/nodejs/node_modules/@opentelemetry/sdk-trace-node/build/src/NodeTracerProvider.js:28:15)
    at initializeProvider (/opt/wrapper.js:81:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

If anyone has any information about the stability of logs with this bug, please let us know. Thanks for your help.

**Comment by Chuckytuh** [comment]
It seems that BasicTracerProvider is attempting to register the default propagators as obtained from the default environment https://github.com/open-telemetry/opentelemetry-js/blob/v1.1.1/packages/opentelemetry-sdk-trace-base/src/BasicTracerProvider.ts#L141 causing the error https://github.com/open-telemetry/opentelemetry-js-api/blob/bafcf0d0756e6ecc79fcc75f221b9dd17641eba5/src/internal/global-utils.ts#L46-L49 to be written.

Based on the comment https://github.com/aws-observability/aws-otel-lambda/blob/main/nodejs/wrapper-adot/src/adot-extension.ts#L13 maybe it makes sense to open an issue on https://github.com/open-telemetry/opentelemetry-lambda instead. The fix *seems* to be 
```typescript
    let sdkRegistrationConfig = {
        propagator: null
    };
```

on wrapper.ts

**Comment by raulrojasadl** [comment]
Thank you @Chuckytuh for your answer and suggestion

**Comment by Chuckytuh** [comment]
@raulrojasadl looking closer at this, it seems that the way forward is to use the ability to extend the AWS Lambda Layer using the extension points such as `global.configureSdkRegistration`. If you're not familiar with those, basically you want to create a new JS module, e.g. "instrumentation.js" with the content:
```javascript
global.configureSdkRegistration = (defaultSdkRegistration) => {
    return {
        propagator: null
    }
};
```

then you need to pre-load it on the layer and you do that by using `NODE_OPTIONS=--require /var/task/instrumentation.js`.  `NODE_OPTIONS` is an environment variable that you'll need to set to your AWS Lambda Functions

**Comment by raulrojasadl** [comment]
@Chuckytuh you make a great contribution, thank you very much for your kind help.
