### ISSUE TITLE
The definition of SpanAttributeValue (and AttributeValue) does represent all possible states of the proto KeyValue specification

### ISSUE THREAD

**Issue by MSNev** [open-telemetry/opentelemetry-js-api#161]
Span attributes (and by extension event attributes) [are defined in the js api as](https://github.com/open-telemetry/opentelemetry-js-api/blob/main/src/common/Attributes.ts#L26-L37)

```TypeScript
/**
 * Attribute values may be any non-nullish primitive value except an object.
 *
 * null or undefined attribute values are invalid and will result in undefined behavior.
 */
export type AttributeValue =
    | string
    | number
    | boolean
    | Array<null | undefined | string>
    | Array<null | undefined | number>
    | Array<null | undefined | boolean>;
```

However, the [proto defintion is](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L257
)
```
    // attributes is a collection of attribute key/value pairs on the event.
    // Attribute keys MUST be unique (it is not allowed to have more than one
    // attribute with the same key).
    repeated opentelemetry.proto.common.v1.KeyValue attributes = 3;
```

With [KeyValue](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L61-L66) defined as taking AnyValue
```
// KeyValue is a key-value pair that is used to store Span attributes, Link
// attributes, etc.
message KeyValue {
  string key = 1;
  AnyValue value = 2;
}
```

Which means that attributes for a span / event "should" support nested objects, but the api specification blocks this.

**Comment by MSNev** [comment]
Raised [spec issue highlighting the same issue with the spec](https://github.com/open-telemetry/opentelemetry-specification/issues/2581)

**Comment by dyladan** [comment]
This is not a bug. The specification does not state that the API should support nested attributes and there are many representable states in proto that are not possible to actually achieve with a well-behaved API and SDK.

**Comment by dyladan** [comment]
I suggest you close this until the spec issue linked is accepted, or at least convert it to a tracker for a potential prototype implementation for that change.

**Comment by MSNev** [comment]
Agree, when it comes to implementing Logs which does support the nested attributes we will probably need to implement an extended type.
