### ISSUE TITLE
Setbaggage should update only current context.

### ISSUE THREAD

**Issue by indolent-developer** [open-telemetry/opentelemetry-js-api#168]
https://github.com/open-telemetry/opentelemetry-js-api/blob/e1745d19b9bdfd1af7d805a6b2c32a5a5dbf4d15/src/baggage/context-helpers.ts#L36-L44

/**
 * Store a baggage in the given context
 *
 * @param {Context} Context that manage all context values
 * @param {Baggage} baggage that will be set in the actual context
 */
export function setBaggage(context: Context, baggage: Baggage): Context {
  return context.setValue(BAGGAGE_KEY, baggage);
}

seems like setbaggage creates a new context when it should not ?

**Comment by vmarchaud** [comment]
The context API is by design (and by requirement) immutable, that means we always create new context when mutating it that you must apply with `context.with`

**Comment by indolent-developer** [comment]
the documentation of method says it. "Store a baggage in the given context" or we update the docs. There has to be some way to add baggage to current context ?  Ideally every context should then some with empty baggage so that I don't have to create new context just to add a  new baggage.

**Comment by vmarchaud** [comment]
It's not possible to modify the current state with the current API (related spec: https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/context).
If you want to set the baggage, you should use:
```ts
context.with(setBaggage(context.active(), myBaggage), () => {
 // your baggage is within this context
})
```

I agree that the documentation could be clearer stating that the baggage will be set on a newly created context

**Comment by indolent-developer** [comment]
add new items to baggage should be allowed ? We do need a way to add items to baggage of current context. What do you think ?

**Comment by Flarna** [comment]
similar as for context. [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.12.0/specification/baggage/api.md) tells also the baggage is immutable and set/remove must return a new baggage

**Comment by dmathieu** [comment]
The API does provide a way to set the baggage, and get a new context (the context being immutable, by definition, it cannot be updated). That's the code sample given by @vmarchaud earlier.
Get a new context, and either provide it to other methods, or set it as the current global one using `context.with`.

**Comment by indolent-developer** [comment]
Thanks for all the support folks. I will evaluate how to go ahead based on feedback.
