### ISSUE TITLE
Enhance tracing in otel-demo for v1 release

### ISSUE THREAD

**Issue by cartersocha** [open-telemetry/opentelemetry-js-api#169]
Tracing instrumentation needs to be enhanced in the community demo in preparation for the v1 release. 

Referencing issue:
https://github.com/open-telemetry/opentelemetry-demo/issues/53

**Comment by dyladan** [comment]
This isn't really very helpful. Are you asking the JS maintainers to do something here?

**Comment by cartersocha** [comment]
We’ll just track it in the demo repo.
