### ISSUE TITLE
Need a way to get the root span's duration

### ISSUE THREAD

**Issue by AadharshR** [open-telemetry/opentelemetry-js-api#170]
In opentelemetry js, we can get the spanContext and the corresponding trace Id. But with the given trace Id, we are not able to perform operations like getting the duration from the root span to current span.

If we get the duration present in currentSpan, it only prints the current span's duration and not from the root span.

Can anyone please help me on this?

**Comment by dyladan** [comment]
What do you mean "duration from root span to current span"? Are you trying to figure out the duration between the root span start and the current span start? You are correct that is not possible to get timing information using API methods. Can you explain what use case you are trying to solve here?

**Comment by AadharshR** [comment]
Yes, I am trying to figure out the time between start and current span start. I have a use case where there is a need to calculate the time taken by all the spans from the start to the current span when the application gets a request.

**Comment by Flarna** [comment]
The root span may be on a different process which runs on a different machine. So really hard to get via OTel API.
Even if the root span is in the same process in some app it may be already ended, exported and removed from memory.

Calculations like that ones you propose are not intended for the traced process, they should be done in the backend which has the full picture and does the correlation of all spans participating in a trace.

**Comment by dyladan** [comment]
We also don't keep a "registry" of spans locally. There is no mechanism in the SDK to look up even local spans by ID since storing all spans would leak memory

**Comment by dyladan** [comment]
Closing as this is impossible with the current architecture and spec
