### ISSUE TITLE
`ContextManager.bind` with a dynamic context

### ISSUE THREAD

**Issue by seemk** [open-telemetry/opentelemetry-js-api#24]
I stumbled upon an issue where it would be useful to additionally have a `bind` method which does not take a context argument, but a function returning a context. It's useful when binding event emitters as some of the emitted events might have different context active based on event types.

What do you think, would there be room for such a method?

Rough sketch (naming, parameter types of the callback uncertain)
```typescript
public bind<T>(target: T, getContext: () => Context): T
```

More context here: https://github.com/open-telemetry/opentelemetry-js/pull/2037

**Comment by dyladan** [comment]
Can you provide a motivating example of a usecase which requires such a feature? Not a theoretical explanation but an actual feature you would like to implement.
