### ISSUE TITLE
Consider moving setSpan()/getSpan() to its related subsection

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-js-api#40]
That is, that it is accessed through `opentelemetry.trace` instead of `opentelemetry` - which is followed by other SIGs, as the idea is overall having each concern have exclusive logical access to its own key/slot. Likewise for the Baggage portion.

Not a strong feeling though, as things are slightly differently organized for JS. For your consideration.

**Comment by dyladan** [comment]
This was done in order to be friendlier to automatic minifiers (important for browser uses). `trace.getSpan` can only be minified to `a.getSpan` where `getSpan` can be minified to a single letter function.

**Comment by vmarchaud** [comment]
We discussed this at SIG and we decided that the understability outweight the minification issue, i'll update all the top level helpers to be on each API namespace
