### ISSUE TITLE
Consider moving the diag/ section to core

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-js-api#42]
Not a strong feeling on this, but you may consider moving `diag/` to `opentelemetry-js/core` as it has actual implementation bits (similarly, other SIGs have additional packages/sections for such components). Not sure about any technical need for it at this level, so it's up to the maintainers to decide this ;)

**Comment by dyladan** [comment]
There was a need to have some way to diagnose failures with the setup process, or in the absence of an SDK. If the SDK fails to register, we did not want to log directly to console as this could break some applications that depend on stdout/stderr format.
