### ISSUE TITLE
[spec] Do not export NOOP implementations

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-api#50]
The NOOP implementations are currently exported. Particularly the NOOP tracer is used to create NOOP spans. After #51, this will no longer be required. Because the specification does not say to export NOOP implementations, we should remove their exports before 1.0

**Comment by Flarna** [comment]
As far as I know this is already the case.

Refs: https://github.com/open-telemetry/opentelemetry-js/pull/1899

**Comment by dyladan** [comment]
We do export NonRecordingSpan. The spec requires us not to. After #51 it will be possible to create one using that method so we will no longer have to export the constructor directly.

**Comment by dyladan** [comment]
@Flarna updated description

**Comment by dyladan** [comment]
Done in #46
