### ISSUE TITLE
Diag logger has no context while using OT in large system

### ISSUE THREAD

**Issue by Asafb26** [open-telemetry/opentelemetry-js-api#52]
Diag logger has a really crucial part while debugging a host - for tracing issues or even a non-related logic issue.
Currently, the logs dumped by the diag logger have no context, we cannot understand if the log arrived from OT or anywhere else.
I guess that we need to label it somehow - a by static label `[OpenTelemetry]` or custom label for the client choice.

**Comment by vmarchaud** [comment]
For context this was discussed in https://github.com/open-telemetry/opentelemetry-js/issues/2104

**Comment by dyladan** [comment]
per-package namespaces are great but there might be value in a host prefix too.
