### ISSUE TITLE
Use whole spancontext for link

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-api#57]
From the spec:

>A Link is structurally defined by the following properties:
>
>- SpanContext of the Span to link to.
>- Zero or more Attributes further describing the link.

Seems pretty clear to me that the link should expose the whole SpanContext including the trace state.

_Originally posted by @dyladan in https://github.com/open-telemetry/opentelemetry-js-api/issues/36#issuecomment-831239711_

Currently our `Link` is an object that shares some properties with `SpanContext`. Should we (1) add the missing properties to `Link` or should we (2) make it `type Link = { spanContext: SpanContext, attributes: Attributes }`?

To me, the spec seems to imply 2 is the more "correct" choice, but 1 is the less breaking change.

**Comment by blumamir** [comment]
I vote for (2).
Seems like the right time to do things more correctly with the cost of minor breaking change.
Also, Links are not in wide use currently so it won't break much.

**Comment by dyladan** [comment]
I think they're used by at least the GCP exporter so they might be used more than you think.

**Comment by dyladan** [comment]
I would also vote for 2

**Comment by blumamir** [comment]
> I think they're used by at least the GCP exporter so they might be used more than you think.

I also use them in `aws-sdk` instrumentation for implementing the messaging systems semantic convention specification for batch receiving.
But it should be a very easy fix.
