### ISSUE TITLE
npm dist tag 'latest' should match the `latest` for core packages

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-js-api#72]
users usually install packages with the `latest` tag which is the default for npm and yarn:
```
npm install @opentelemetry/node @opentelemetry/api
yarn add @opentelemetry/node @opentelemetry/api
```

Currently, user will get incompatible versions as latest core packages has peer dependency on `^1.0.0-rc.0` (or `1.0.0-rc.0` after [this](https://github.com/open-telemetry/opentelemetry-js/pull/2213) PR), but api npm latest points to `0.18.1`.
So a user creating a fresh installation will have to run something like:
```
yarn add @opentelemetry/node @opentelemetry/api@1.0.0-rc.0
```
which can be missed very easily and create confusions.

I suggest making the default versioning consistent between core and api packages, by publishing `rc.0` version as "latest" in npm if it is possible

**Comment by dyladan** [comment]
`latest` tags now match
