### ISSUE TITLE
Maintainer Vote: `api.context.bind` `context` argument optional or not

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-js-api#86]
Pursuant to the [community guidelines](https://github.com/open-telemetry/community/blob/main/community-membership.md#resolving-technical-conflicts-within-a-sig), a vote of the maintainers is required to resolve #78.

Should the context method `bind` require an explicit `context` argument or use `context.active()` as default?

**Comment by dyladan** [comment]
I vote for explicit context argument

**Comment by vmarchaud** [comment]
I vote for requiring a context

**Comment by obecny** [comment]
I vote for context to be optional as it is now.
