### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by jonathanblancor** [open-telemetry/opentelemetry-js-api#87]
I am using this library through `@azure/identity` and is throwing a `Circular dependency` warning. I have placed the text warning and picture.

I am importing `@azure` libraries as:
`import * as azureIdentity from '@azure/identity';`
`import * as appConfig from '@azure/app-configuration';`

Warning:
`Circular dependency: node_modules\@azure\identity\node_modules\@opentelemetry\api\build\src\index.js -> node_modules\@azure\inode_modules\@opentelemetry\api\build\src\internal\global-utils.js -> node_modules\@azure\identity\node_modules\@opentelemetr
Circular dependency: node_modules\@azure\identity\node_modules\@opentelemetry\api\build\src\index.js -> node_modules\@azure\inode_modules\@opentelemetry\api\build\src\internal\global-utils.js ->  C:\Users\JBlanco\Documents\MFE - Product\node_modules\\@azure\identity\node_modules\@opentelemetry\api\build\src\index.js
Circular dependency: node_modules\@azure\core-http\node_modules\@opentelemetry\api\build\src\index.js -> node_modules\@azure\tp\node_modules\@opentelemetry\api\build\src\internal\global-utils.js -> node_modules\@azure\core-http\node_modules\@opentele
Circular dependency: node_modules\@azure\core-http\node_modules\@opentelemetry\api\build\src\index.js -> node_modules\@azure\tp\node_modules\@opentelemetry\api\build\src\internal\global-utils.js ->  C:\Users\JBlanco\Documents\MFE - Product\node_modulules\@azure\core-http\node_modules\@opentelemetry\api\build\src\index.js`

![image](https://user-images.githubusercontent.com/13365903/120533055-5738d400-c3ae-11eb-9446-b49f7f16d2a3.png)

Any other information needed please let me know.

**Comment by vreynolds** [comment]
Sounds like an issue with `@azure/identity`, since `opentelemetry-js-api` doesn't depend on azure. Could you raise it in [the azure repo](https://github.com/Azure/azure-sdk-for-js/issues)?

**Comment by dyladan** [comment]
`@opentelemetry/api` actually has no circular dependencies. It sounds like most likely `@azure/identity` is depending on an internal module of `@opentelemetry/api` or even patching it which causes the dependency circle.

**Comment by sadasant** [comment]
Hello! I’m from the Azure SDK team.

I’m trying to figure out what’s going on. It seems to me that there is a circular dependency indeed.

For context, we’ve been using version 0.10.2 of @opentelemetry/api, could there have been a circular dependency in that version? I don’t see the internal folder you’re referring to there. ccL @dyladan 

We’re working on upgrading to version 0.20.0: https://github.com/Azure/azure-sdk-for-js/pull/15672 - based on the folder structure, I believe it may help, but I haven’t been able to confirm (we will in the following days).

**Comment by dyladan** [comment]
Seems you're right.

**Comment by maorleger** [comment]
I updated to @opentelemetry/api@1.0.1 which should contain the fix; however, I see another circular dependency that is unresolved:

I believe this is the problem: `src/index.ts` depends on `src/baggage/utils.ts` which depends on `src/index.ts`

Rollup errors: 

```
Error: Circular dependency: ../../../common/temp/node_modules/.pnpm/@opentelemetry/api@1.0.1/node_modules/@opentelemetry/api/build/esm/index.js -> ../../../common/temp/node_modules/.pnpm/@opentelemetry/api@1.0.1/node_modules/@opentelemetry/api/build/esm/baggage/utils.js -> ../../../common/temp/node_modules/.pnpm/@opentelemetry/api@1.0.1/node_modules/@opentelemetry/api/build/esm/index.js
```

Let me know if you'd rather me open a new issue or if you need any more information!
