### ISSUE TITLE
Consider renaming Link#context -> Link#spanContext

### ISSUE THREAD

**Issue by aabmass** [open-telemetry/opentelemetry-js-api#91]
`Span#context` was renamed in https://github.com/open-telemetry/opentelemetry-js-api/pull/45. For consistency, it would be nice if link did the same. https://github.com/open-telemetry/opentelemetry-js-api/blob/9b3f9c75a57190841b5f091933932386f63a62ac/src/trace/link.ts#L37

This is a minor ask – if we don't want to create more API churn this can be closed 🙂

**Comment by dyladan** [comment]
This will not make it into the 1.0 release. We can add it after 1.0 as a minor addition and mark the previous property as deprecated.

**Comment by Flarna** [comment]
Is there already a deprecation workflow defined?
For example node.js has [3 types of deprecations](https://github.com/nodejs/node/blob/master/doc/guides/collaborator-guide.md#deprecations) where doc deprecated is the only one which is not semver major.

**Comment by dyladan** [comment]
The [spec versioning doc](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md) has only made affordances for deprecating whole signals, not individual API methods and properties.

I will open a PR with an official deprecation strategy along these lines:

1. Add `@deprecated` tsdoc flag with a note pointing to the new function or some upgrade strategy if applicable.
2. In the next major release, all previously `@deprecated` functions are removed. This will likely be much later.

**Comment by dyladan** [comment]
Good suggestion. I think at least a whole major cycle is likely to be extremely long. How about next major release unless the release happens within 6 months of deprecation, else the removal must wait for the next major release after that.

**Comment by dyladan** [comment]
I would also say introducing a `@deprecated` flag is a semver-minor change, not patch, and it must come along with a documented alternative solution.

**Comment by dyladan** [comment]
This rename is a breaking change and I don't see a strong benefit to deprecate the old name. If someone thinks this is causing unnecessary confusion they can open an issue in https://github.com/open-telemetry/opentelemetry-js as this package is moving there.
